/* This file ist generated by the program DSLMethodsGenerator. DO NOT EDIT IT MANUALLY! */

namespace BlazorDSL {
    public static partial class Html {
        
            public static Attribute abbr(string className)
                => new Attribute("abbr", className);

            public static Attribute accept(string className)
                => new Attribute("accept", className);

            public static Attribute acceptCharset(string className)
                => new Attribute("accept-charset", className);

            public static Attribute accesskey(string className)
                => new Attribute("accesskey", className);

            public static Attribute action(string className)
                => new Attribute("action", className);

            public static Attribute allow(string className)
                => new Attribute("allow", className);

            public static Attribute allowfullscreen(string className)
                => new Attribute("allowfullscreen", className);

            public static Attribute alpha(string className)
                => new Attribute("alpha", className);

            public static Attribute alt(string className)
                => new Attribute("alt", className);

            public static Attribute @as(string className)
                => new Attribute("as", className);

            public static Attribute async(string className)
                => new Attribute("async", className);

            public static Attribute autocapitalize(string className)
                => new Attribute("autocapitalize", className);

            public static Attribute autocomplete(string className)
                => new Attribute("autocomplete", className);

            public static Attribute autocorrect(string className)
                => new Attribute("autocorrect", className);

            public static Attribute autofocus(string className)
                => new Attribute("autofocus", className);

            public static Attribute autoplay(string className)
                => new Attribute("autoplay", className);

            public static Attribute blocking(string className)
                => new Attribute("blocking", className);

            public static Attribute charset(string className)
                => new Attribute("charset", className);

            public static Attribute @checked(string className)
                => new Attribute("checked", className);

            public static Attribute cite(string className)
                => new Attribute("cite", className);

            public static Attribute className(string className)
                => new Attribute("class", className);

            public static Attribute closedby(string className)
                => new Attribute("closedby", className);

            public static Attribute color(string className)
                => new Attribute("color", className);

            public static Attribute colorspace(string className)
                => new Attribute("colorspace", className);

            public static Attribute cols(string className)
                => new Attribute("cols", className);

            public static Attribute colspan(string className)
                => new Attribute("colspan", className);

            public static Attribute content(string className)
                => new Attribute("content", className);

            public static Attribute contenteditable(string className)
                => new Attribute("contenteditable", className);

            public static Attribute controls(string className)
                => new Attribute("controls", className);

            public static Attribute coords(string className)
                => new Attribute("coords", className);

            public static Attribute crossorigin(string className)
                => new Attribute("crossorigin", className);

            public static Attribute data(string className)
                => new Attribute("data", className);

            public static Attribute datetime(string className)
                => new Attribute("datetime", className);

            public static Attribute decoding(string className)
                => new Attribute("decoding", className);

            public static Attribute @default(string className)
                => new Attribute("default", className);

            public static Attribute defer(string className)
                => new Attribute("defer", className);

            public static Attribute dir(string className)
                => new Attribute("dir", className);

            public static Attribute dirname(string className)
                => new Attribute("dirname", className);

            public static Attribute disabled(string className)
                => new Attribute("disabled", className);

            public static Attribute download(string className)
                => new Attribute("download", className);

            public static Attribute draggable(string className)
                => new Attribute("draggable", className);

            public static Attribute enctype(string className)
                => new Attribute("enctype", className);

            public static Attribute enterkeyhint(string className)
                => new Attribute("enterkeyhint", className);

            public static Attribute fetchpriority(string className)
                => new Attribute("fetchpriority", className);

            public static Attribute @for(string className)
                => new Attribute("for", className);

            public static Attribute form(string className)
                => new Attribute("form", className);

            public static Attribute formaction(string className)
                => new Attribute("formaction", className);

            public static Attribute formenctype(string className)
                => new Attribute("formenctype", className);

            public static Attribute formmethod(string className)
                => new Attribute("formmethod", className);

            public static Attribute formnovalidate(string className)
                => new Attribute("formnovalidate", className);

            public static Attribute formtarget(string className)
                => new Attribute("formtarget", className);

            public static Attribute headers(string className)
                => new Attribute("headers", className);

            public static Attribute height(string className)
                => new Attribute("height", className);

            public static Attribute hidden(string className)
                => new Attribute("hidden", className);

            public static Attribute high(string className)
                => new Attribute("high", className);

            public static Attribute href(string className)
                => new Attribute("href", className);

            public static Attribute hreflang(string className)
                => new Attribute("hreflang", className);

            public static Attribute httpEquiv(string className)
                => new Attribute("http-equiv", className);

            public static Attribute id(string className)
                => new Attribute("id", className);

            public static Attribute imagesizes(string className)
                => new Attribute("imagesizes", className);

            public static Attribute imagesrcset(string className)
                => new Attribute("imagesrcset", className);

            public static Attribute inert(string className)
                => new Attribute("inert", className);

            public static Attribute inputmode(string className)
                => new Attribute("inputmode", className);

            public static Attribute integrity(string className)
                => new Attribute("integrity", className);

            public static Attribute @is(string className)
                => new Attribute("is", className);

            public static Attribute ismap(string className)
                => new Attribute("ismap", className);

            public static Attribute itemid(string className)
                => new Attribute("itemid", className);

            public static Attribute itemprop(string className)
                => new Attribute("itemprop", className);

            public static Attribute itemref(string className)
                => new Attribute("itemref", className);

            public static Attribute itemscope(string className)
                => new Attribute("itemscope", className);

            public static Attribute itemtype(string className)
                => new Attribute("itemtype", className);

            public static Attribute kind(string className)
                => new Attribute("kind", className);

            public static Attribute label(string className)
                => new Attribute("label", className);

            public static Attribute lang(string className)
                => new Attribute("lang", className);

            public static Attribute list(string className)
                => new Attribute("list", className);

            public static Attribute loading(string className)
                => new Attribute("loading", className);

            public static Attribute loop(string className)
                => new Attribute("loop", className);

            public static Attribute low(string className)
                => new Attribute("low", className);

            public static Attribute max(string className)
                => new Attribute("max", className);

            public static Attribute maxlength(string className)
                => new Attribute("maxlength", className);

            public static Attribute media(string className)
                => new Attribute("media", className);

            public static Attribute method(string className)
                => new Attribute("method", className);

            public static Attribute min(string className)
                => new Attribute("min", className);

            public static Attribute minlength(string className)
                => new Attribute("minlength", className);

            public static Attribute multiple(string className)
                => new Attribute("multiple", className);

            public static Attribute muted(string className)
                => new Attribute("muted", className);

            public static Attribute name(string className)
                => new Attribute("name", className);

            public static Attribute nomodule(string className)
                => new Attribute("nomodule", className);

            public static Attribute nonce(string className)
                => new Attribute("nonce", className);

            public static Attribute novalidate(string className)
                => new Attribute("novalidate", className);

            public static Attribute open(string className)
                => new Attribute("open", className);

            public static Attribute optimum(string className)
                => new Attribute("optimum", className);

            public static Attribute pattern(string className)
                => new Attribute("pattern", className);

            public static Attribute ping(string className)
                => new Attribute("ping", className);

            public static Attribute placeholder(string className)
                => new Attribute("placeholder", className);

            public static Attribute playsinline(string className)
                => new Attribute("playsinline", className);

            public static Attribute popover(string className)
                => new Attribute("popover", className);

            public static Attribute popovertarget(string className)
                => new Attribute("popovertarget", className);

            public static Attribute popovertargetaction(string className)
                => new Attribute("popovertargetaction", className);

            public static Attribute poster(string className)
                => new Attribute("poster", className);

            public static Attribute preload(string className)
                => new Attribute("preload", className);

            public static Attribute @readonly(string className)
                => new Attribute("readonly", className);

            public static Attribute referrerpolicy(string className)
                => new Attribute("referrerpolicy", className);

            public static Attribute rel(string className)
                => new Attribute("rel", className);

            public static Attribute required(string className)
                => new Attribute("required", className);

            public static Attribute reversed(string className)
                => new Attribute("reversed", className);

            public static Attribute rows(string className)
                => new Attribute("rows", className);

            public static Attribute rowspan(string className)
                => new Attribute("rowspan", className);

            public static Attribute sandbox(string className)
                => new Attribute("sandbox", className);

            public static Attribute scope(string className)
                => new Attribute("scope", className);

            public static Attribute selected(string className)
                => new Attribute("selected", className);

            public static Attribute shadowrootclonable(string className)
                => new Attribute("shadowrootclonable", className);

            public static Attribute shadowrootdelegatesfocus(string className)
                => new Attribute("shadowrootdelegatesfocus", className);

            public static Attribute shadowrootmode(string className)
                => new Attribute("shadowrootmode", className);

            public static Attribute shadowrootserializable(string className)
                => new Attribute("shadowrootserializable", className);

            public static Attribute shape(string className)
                => new Attribute("shape", className);

            public static Attribute size(string className)
                => new Attribute("size", className);

            public static Attribute sizes(string className)
                => new Attribute("sizes", className);

            public static Attribute slot(string className)
                => new Attribute("slot", className);

            public static Attribute span(string className)
                => new Attribute("span", className);

            public static Attribute spellcheck(string className)
                => new Attribute("spellcheck", className);

            public static Attribute src(string className)
                => new Attribute("src", className);

            public static Attribute srcdoc(string className)
                => new Attribute("srcdoc", className);

            public static Attribute srclang(string className)
                => new Attribute("srclang", className);

            public static Attribute srcset(string className)
                => new Attribute("srcset", className);

            public static Attribute start(string className)
                => new Attribute("start", className);

            public static Attribute step(string className)
                => new Attribute("step", className);

            public static Attribute style(string className)
                => new Attribute("style", className);

            public static Attribute tabindex(string className)
                => new Attribute("tabindex", className);

            public static Attribute target(string className)
                => new Attribute("target", className);

            public static Attribute title(string className)
                => new Attribute("title", className);

            public static Attribute translate(string className)
                => new Attribute("translate", className);

            public static Attribute type(string className)
                => new Attribute("type", className);

            public static Attribute usemap(string className)
                => new Attribute("usemap", className);

            public static Attribute value(string className)
                => new Attribute("value", className);

            public static Attribute width(string className)
                => new Attribute("width", className);

            public static Attribute wrap(string className)
                => new Attribute("wrap", className);

            public static Attribute writingsuggestions(string className)
                => new Attribute("writingsuggestions", className);
    }
}
