/* This file ist generated by the program DSLMethodsGenerator. DO NOT EDIT IT MANUALLY! */

namespace BlazorDSL {
    public static partial class Html {
        
            public static Attribute abbr(string className)
                => new SimpleAttribute("abbr", className);

            public static Attribute accept(string className)
                => new SimpleAttribute("accept", className);

            public static Attribute acceptCharset(string className)
                => new SimpleAttribute("accept-charset", className);

            public static Attribute accesskey(string className)
                => new SimpleAttribute("accesskey", className);

            public static Attribute action(string className)
                => new SimpleAttribute("action", className);

            public static Attribute allow(string className)
                => new SimpleAttribute("allow", className);

            public static Attribute allowfullscreen(string className)
                => new SimpleAttribute("allowfullscreen", className);

            public static Attribute alpha(string className)
                => new SimpleAttribute("alpha", className);

            public static Attribute alt(string className)
                => new SimpleAttribute("alt", className);

            public static Attribute @as(string className)
                => new SimpleAttribute("as", className);

            public static Attribute async(string className)
                => new SimpleAttribute("async", className);

            public static Attribute autocapitalize(string className)
                => new SimpleAttribute("autocapitalize", className);

            public static Attribute autocomplete(string className)
                => new SimpleAttribute("autocomplete", className);

            public static Attribute autocorrect(string className)
                => new SimpleAttribute("autocorrect", className);

            public static Attribute autofocus(string className)
                => new SimpleAttribute("autofocus", className);

            public static Attribute autoplay(string className)
                => new SimpleAttribute("autoplay", className);

            public static Attribute blocking(string className)
                => new SimpleAttribute("blocking", className);

            public static Attribute charset(string className)
                => new SimpleAttribute("charset", className);

            public static Attribute @checked(string className)
                => new SimpleAttribute("checked", className);

            public static Attribute cite(string className)
                => new SimpleAttribute("cite", className);

            public static Attribute className(string className)
                => new SimpleAttribute("class", className);

            public static Attribute closedby(string className)
                => new SimpleAttribute("closedby", className);

            public static Attribute color(string className)
                => new SimpleAttribute("color", className);

            public static Attribute colorspace(string className)
                => new SimpleAttribute("colorspace", className);

            public static Attribute cols(string className)
                => new SimpleAttribute("cols", className);

            public static Attribute colspan(string className)
                => new SimpleAttribute("colspan", className);

            public static Attribute content(string className)
                => new SimpleAttribute("content", className);

            public static Attribute contenteditable(string className)
                => new SimpleAttribute("contenteditable", className);

            public static Attribute controls(string className)
                => new SimpleAttribute("controls", className);

            public static Attribute coords(string className)
                => new SimpleAttribute("coords", className);

            public static Attribute crossorigin(string className)
                => new SimpleAttribute("crossorigin", className);

            public static Attribute data(string className)
                => new SimpleAttribute("data", className);

            public static Attribute datetime(string className)
                => new SimpleAttribute("datetime", className);

            public static Attribute decoding(string className)
                => new SimpleAttribute("decoding", className);

            public static Attribute @default(string className)
                => new SimpleAttribute("default", className);

            public static Attribute defer(string className)
                => new SimpleAttribute("defer", className);

            public static Attribute dir(string className)
                => new SimpleAttribute("dir", className);

            public static Attribute dirname(string className)
                => new SimpleAttribute("dirname", className);

            public static Attribute disabled(string className)
                => new SimpleAttribute("disabled", className);

            public static Attribute download(string className)
                => new SimpleAttribute("download", className);

            public static Attribute draggable(string className)
                => new SimpleAttribute("draggable", className);

            public static Attribute enctype(string className)
                => new SimpleAttribute("enctype", className);

            public static Attribute enterkeyhint(string className)
                => new SimpleAttribute("enterkeyhint", className);

            public static Attribute fetchpriority(string className)
                => new SimpleAttribute("fetchpriority", className);

            public static Attribute @for(string className)
                => new SimpleAttribute("for", className);

            public static Attribute form(string className)
                => new SimpleAttribute("form", className);

            public static Attribute formaction(string className)
                => new SimpleAttribute("formaction", className);

            public static Attribute formenctype(string className)
                => new SimpleAttribute("formenctype", className);

            public static Attribute formmethod(string className)
                => new SimpleAttribute("formmethod", className);

            public static Attribute formnovalidate(string className)
                => new SimpleAttribute("formnovalidate", className);

            public static Attribute formtarget(string className)
                => new SimpleAttribute("formtarget", className);

            public static Attribute headers(string className)
                => new SimpleAttribute("headers", className);

            public static Attribute height(string className)
                => new SimpleAttribute("height", className);

            public static Attribute hidden(string className)
                => new SimpleAttribute("hidden", className);

            public static Attribute high(string className)
                => new SimpleAttribute("high", className);

            public static Attribute href(string className)
                => new SimpleAttribute("href", className);

            public static Attribute hreflang(string className)
                => new SimpleAttribute("hreflang", className);

            public static Attribute httpEquiv(string className)
                => new SimpleAttribute("http-equiv", className);

            public static Attribute id(string className)
                => new SimpleAttribute("id", className);

            public static Attribute imagesizes(string className)
                => new SimpleAttribute("imagesizes", className);

            public static Attribute imagesrcset(string className)
                => new SimpleAttribute("imagesrcset", className);

            public static Attribute inert(string className)
                => new SimpleAttribute("inert", className);

            public static Attribute inputmode(string className)
                => new SimpleAttribute("inputmode", className);

            public static Attribute integrity(string className)
                => new SimpleAttribute("integrity", className);

            public static Attribute @is(string className)
                => new SimpleAttribute("is", className);

            public static Attribute ismap(string className)
                => new SimpleAttribute("ismap", className);

            public static Attribute itemid(string className)
                => new SimpleAttribute("itemid", className);

            public static Attribute itemprop(string className)
                => new SimpleAttribute("itemprop", className);

            public static Attribute itemref(string className)
                => new SimpleAttribute("itemref", className);

            public static Attribute itemscope(string className)
                => new SimpleAttribute("itemscope", className);

            public static Attribute itemtype(string className)
                => new SimpleAttribute("itemtype", className);

            public static Attribute kind(string className)
                => new SimpleAttribute("kind", className);

            public static Attribute label(string className)
                => new SimpleAttribute("label", className);

            public static Attribute lang(string className)
                => new SimpleAttribute("lang", className);

            public static Attribute list(string className)
                => new SimpleAttribute("list", className);

            public static Attribute loading(string className)
                => new SimpleAttribute("loading", className);

            public static Attribute loop(string className)
                => new SimpleAttribute("loop", className);

            public static Attribute low(string className)
                => new SimpleAttribute("low", className);

            public static Attribute max(string className)
                => new SimpleAttribute("max", className);

            public static Attribute maxlength(string className)
                => new SimpleAttribute("maxlength", className);

            public static Attribute media(string className)
                => new SimpleAttribute("media", className);

            public static Attribute method(string className)
                => new SimpleAttribute("method", className);

            public static Attribute min(string className)
                => new SimpleAttribute("min", className);

            public static Attribute minlength(string className)
                => new SimpleAttribute("minlength", className);

            public static Attribute multiple(string className)
                => new SimpleAttribute("multiple", className);

            public static Attribute muted(string className)
                => new SimpleAttribute("muted", className);

            public static Attribute name(string className)
                => new SimpleAttribute("name", className);

            public static Attribute nomodule(string className)
                => new SimpleAttribute("nomodule", className);

            public static Attribute nonce(string className)
                => new SimpleAttribute("nonce", className);

            public static Attribute novalidate(string className)
                => new SimpleAttribute("novalidate", className);

            public static Attribute open(string className)
                => new SimpleAttribute("open", className);

            public static Attribute optimum(string className)
                => new SimpleAttribute("optimum", className);

            public static Attribute pattern(string className)
                => new SimpleAttribute("pattern", className);

            public static Attribute ping(string className)
                => new SimpleAttribute("ping", className);

            public static Attribute placeholder(string className)
                => new SimpleAttribute("placeholder", className);

            public static Attribute playsinline(string className)
                => new SimpleAttribute("playsinline", className);

            public static Attribute popover(string className)
                => new SimpleAttribute("popover", className);

            public static Attribute popovertarget(string className)
                => new SimpleAttribute("popovertarget", className);

            public static Attribute popovertargetaction(string className)
                => new SimpleAttribute("popovertargetaction", className);

            public static Attribute poster(string className)
                => new SimpleAttribute("poster", className);

            public static Attribute preload(string className)
                => new SimpleAttribute("preload", className);

            public static Attribute @readonly(string className)
                => new SimpleAttribute("readonly", className);

            public static Attribute referrerpolicy(string className)
                => new SimpleAttribute("referrerpolicy", className);

            public static Attribute rel(string className)
                => new SimpleAttribute("rel", className);

            public static Attribute required(string className)
                => new SimpleAttribute("required", className);

            public static Attribute reversed(string className)
                => new SimpleAttribute("reversed", className);

            public static Attribute rows(string className)
                => new SimpleAttribute("rows", className);

            public static Attribute rowspan(string className)
                => new SimpleAttribute("rowspan", className);

            public static Attribute sandbox(string className)
                => new SimpleAttribute("sandbox", className);

            public static Attribute scope(string className)
                => new SimpleAttribute("scope", className);

            public static Attribute selected(string className)
                => new SimpleAttribute("selected", className);

            public static Attribute shadowrootclonable(string className)
                => new SimpleAttribute("shadowrootclonable", className);

            public static Attribute shadowrootdelegatesfocus(string className)
                => new SimpleAttribute("shadowrootdelegatesfocus", className);

            public static Attribute shadowrootmode(string className)
                => new SimpleAttribute("shadowrootmode", className);

            public static Attribute shadowrootserializable(string className)
                => new SimpleAttribute("shadowrootserializable", className);

            public static Attribute shape(string className)
                => new SimpleAttribute("shape", className);

            public static Attribute size(string className)
                => new SimpleAttribute("size", className);

            public static Attribute sizes(string className)
                => new SimpleAttribute("sizes", className);

            public static Attribute slot(string className)
                => new SimpleAttribute("slot", className);

            public static Attribute span(string className)
                => new SimpleAttribute("span", className);

            public static Attribute spellcheck(string className)
                => new SimpleAttribute("spellcheck", className);

            public static Attribute src(string className)
                => new SimpleAttribute("src", className);

            public static Attribute srcdoc(string className)
                => new SimpleAttribute("srcdoc", className);

            public static Attribute srclang(string className)
                => new SimpleAttribute("srclang", className);

            public static Attribute srcset(string className)
                => new SimpleAttribute("srcset", className);

            public static Attribute start(string className)
                => new SimpleAttribute("start", className);

            public static Attribute step(string className)
                => new SimpleAttribute("step", className);

            public static Attribute style(string className)
                => new SimpleAttribute("style", className);

            public static Attribute tabindex(string className)
                => new SimpleAttribute("tabindex", className);

            public static Attribute target(string className)
                => new SimpleAttribute("target", className);

            public static Attribute title(string className)
                => new SimpleAttribute("title", className);

            public static Attribute translate(string className)
                => new SimpleAttribute("translate", className);

            public static Attribute type(string className)
                => new SimpleAttribute("type", className);

            public static Attribute usemap(string className)
                => new SimpleAttribute("usemap", className);

            public static Attribute value(string className)
                => new SimpleAttribute("value", className);

            public static Attribute width(string className)
                => new SimpleAttribute("width", className);

            public static Attribute wrap(string className)
                => new SimpleAttribute("wrap", className);

            public static Attribute writingsuggestions(string className)
                => new SimpleAttribute("writingsuggestions", className);
    }
}
